main: MYps.c getPIDs.c getPIDState.c getPIDUtime.c getPIDStime.c getPIDVmem.c getPIDcmdline.c
	gcc -o MYps MYps.c getPIDs.c getPIDState.c getPIDUtime.c getPIDStime.c getPIDVmem.c  getPIDcmdline.c -Wall -Werror

clean:
	rm -rf .o MYps